version: "3.9"

services:
  zookeeper:
    image: zookeeper:3.9.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080
    restart: always

  node:
    image: ${DOCKER_REGISTRY-}sequencenode
    restart: always
    build:
      context: SequenceNode
      target: prod
    deploy:
      replicas: 4
    environment:
      - Zookeeper__ConnectionString=zookeeper